language: node_js
node_js:
  - "7"
dist: trusty
sudo: false
addons:
  chrome: stable
  firefox: latest
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run testKarma -- --single-run=true --browsers=ChromeHeadless,FirefoxHeadless
